### ISSUE TITLE
GLMap Style

### ISSUE THREAD

**Issue by Spettacolo83** [GLMap/examples-android#10]
Hello there,
I wonder how I can change the map style for one darker for example for night navigation.
The default style is this:
`mapView.loadStyle(getAssets(), "DefaultStyle.bundle");`
Maybe there are some different in the assets.
Thank you!

**Comment by molind** [comment]
Default style is available at: https://user.getyourmap.com/downloads/free/GLMapDefaultStyle-1.0.1.zip You could change **colors.mapcss** files inside, rename `DefaultStyle.bundle` to `DarkTheme.bundle`. Add manually into project and load as `mapView.loadStyle(getAssets(), "DarkTheme.bundle");`

**Comment by jahir8a** [comment]
Excellent work that you did with this API I congratulate you, a query with the style of maps once you change the styles of the map these must add them to the assets folder or do you have to perform an extra task ?. If possible, you could give me a sample project, besides being new to openstreetmap there are tools to customize it. Thanks in advance
