### ISSUE TITLE
Does it have MapMatching feature for Android?

### ISSUE THREAD

**Issue by anonym24** [GLMap/examples-android#11]
Example: https://farm1.staticflickr.com/530/18518221448_5752e8ab30_o.gif

https://en.wikipedia.org/wiki/Map_matching

**Comment by molind** [comment]
Unfortunately we don't have map matching, like you displayed. But there is GLRoute have findNearestPoint method. And it snaps your point to route. You could easily compute distance between your point and nearest point on route and decide if it fits for you or not.

I'll update documentation. Seems we missing com.getyourmap.glroute package by now.

**Comment by molind** [comment]
Documentation has been updated.
