### ISSUE TITLE
Custom vector tile source

### ISSUE THREAD

**Issue by SergeiMinaev** [GLMap/examples-android#9]
Sorry if I didn't googled it enough, but is there a possibility to use own vector tile source? All I found is GLMapRasterTileSource.
I want to use own source because I need to increase level of detail on small zoom levels.

**Comment by molind** [comment]
It's not possible to plug in custom vector sources because vector renderer optimized for our vector map format and it's not support other app formats. But you could draw any custom data from vector objects. E.g. load your geo data from geojson, then add it on map with MapCSS style.

**Comment by SergeiMinaev** [comment]
Ok, I got it. Thanks!
